server:
  port: 7070
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s

      routes:
        - id: test-service
          uri: http://localhost:8080
          predicates:
            - Path=/test/t1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
