server:
  port: 7070
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
      routes:
        - id: community-service
          uri: lb://COMMUNITY
          predicates:
            - Path=/community/**
        - id: member-service
          uri: lb://ACCOUNT
          predicates:
            - Path=/account/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
