server:
  port: 7070
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s
      routes:
        - id: community-service
          uri: http://54.180.159.115:7070/
          predicates:
            - Path=/community/**
        - id: member-service
          uri: lb://13.124.140.178:7070
          predicates:
            - Path=/account/**
        - id: streaming-service
          uri: lb://13.124.140.178:8080
          predicates:
            - Path=/streaming/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://54.180.159.115:8080/eureka/
